# Autogenerated wrapper script for lwgrp_jll for armv6l-linux-musleabihf-mpi+mpich
export liblwgrp

using MPICH_jll
JLLWrappers.@generate_wrapper_header("lwgrp")
JLLWrappers.@declare_library_product(liblwgrp, "liblwgrp.so")
function __init__()
    JLLWrappers.@generate_init_header(MPICH_jll, MPIPreferences)
    JLLWrappers.@init_library_product(
        liblwgrp,
        "lib/liblwgrp.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
